# Generated by Django 5.1.3 on 2025-12-14 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('sistema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cambiodepartamento',
            name='realizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por'),
        ),
        migrations.AddField(
            model_name='cambiodepartamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_departamento', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='jefe_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jefe_departamento', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
        migrations.AddField(
            model_name='cambiodepartamento',
            name='departamento_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_salida', to='catalogos.departamento', verbose_name='Departamento anterior'),
        ),
        migrations.AddField(
            model_name='cambiodepartamento',
            name='departamento_nuevo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_entrada', to='catalogos.departamento', verbose_name='Departamento nuevo'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='catalogos.estadopais'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institucion_academica', to='sistema.empresa'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institucion',
            name='unidad_usuario',
            field=models.ManyToManyField(related_name='unidad_negocio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departamento',
            name='instituto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='catalogos.institucion'),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradoescolar',
            name='nivel_educativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados_escolares', to='catalogos.niveleducativo'),
        ),
    ]
