# Generated by Django 5.1.3 on 2025-12-14 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_ciudad_estadopais'),
        ('user', '0002_remove_typeuser_grupo_asociado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstatusAlummo',
        ),
        migrations.AddField(
            model_name='ciudad',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='catalogos.estadopais'),
        ),
    ]
