# Generated by Django 5.1.3 on 2025-12-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_delete_estatusalummo_ciudad_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
