# Generated by Django 5.1.3 on 2025-12-14 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalogos', '0003_ciudad_estadopais'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeuser',
            name='grupo_asociado',
        ),
        migrations.RemoveField(
            model_name='usercustomize',
            name='type_user',
        ),
        migrations.RemoveField(
            model_name='usercustomize',
            name='departamento',
        ),
        migrations.CreateModel(
            name='EstudiantePerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('especialidad', models.CharField(blank=True, max_length=50, null=True)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ciudad', to='catalogos.ciudad')),
                ('estado_pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_estado_pais', to='catalogos.estadopais')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_institucion', to='catalogos.institucion')),
                ('nivel_educativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_nivel', to='catalogos.niveleducativo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'estudiante_perfil',
            },
        ),
        migrations.CreateModel(
            name='MaestroPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('tiene_certificado', models.BooleanField(default=False)),
                ('certificado', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_cedula', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ciudad', to='catalogos.ciudad')),
                ('estado_pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_estado_pais', to='catalogos.estadopais')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_institucion', to='catalogos.institucion')),
                ('nivel_educativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_nivel', to='catalogos.niveleducativo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maestro_perfil',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nivel_acceso', models.IntegerField(blank=True, null=True)),
                ('permission', models.ManyToManyField(to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='usercustomize',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='user.role'),
        ),
        migrations.DeleteModel(
            name='AcademicProfile',
        ),
        migrations.DeleteModel(
            name='TypeUser',
        ),
    ]
