# Generated by Django 5.1.3 on 2025-12-14 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_metodopago'),
        ('user', '0002_remove_typeuser_grupo_asociado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudianteperfil',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ciudad', to='catalogos.ciudad'),
        ),
        migrations.AlterField(
            model_name='estudianteperfil',
            name='estado_pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_estado_pais', to='catalogos.estadopais'),
        ),
        migrations.AlterField(
            model_name='estudianteperfil',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_institucion', to='catalogos.institucion'),
        ),
        migrations.AlterField(
            model_name='estudianteperfil',
            name='nivel_educativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_nivel', to='catalogos.niveleducativo'),
        ),
        migrations.AlterField(
            model_name='estudianteperfil',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maestroperfil',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ciudad', to='catalogos.ciudad'),
        ),
        migrations.AlterField(
            model_name='maestroperfil',
            name='estado_pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_estado_pais', to='catalogos.estadopais'),
        ),
        migrations.AlterField(
            model_name='maestroperfil',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_institucion', to='catalogos.institucion'),
        ),
        migrations.AlterField(
            model_name='maestroperfil',
            name='nivel_educativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_nivel', to='catalogos.niveleducativo'),
        ),
        migrations.AlterField(
            model_name='maestroperfil',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
